import type {
  Model,
  Provider,
  Harness,
  Availability,
  Source,
  ChangeHistory,
  HarnessCompat,
} from "./types";

// ---------------------------------------------------------------------------
// NOTE ON DATA PROVENANCE
// ---------------------------------------------------------------------------
// This is a curated SEED dataset meant to demonstrate the full product. Free
// AI-model availability changes constantly. Every row carries a
// `verificationConfidence` and `lastVerifiedAt` so the UI can show freshness.
// Records marked "likely"/"unverified" must be re-verified against the linked
// official source before relying on them. See /admin for the verification queue.
// ---------------------------------------------------------------------------

const SEED_DATE = "2026-08-15";

export const PROVIDERS: Provider[] = [
  {
    id: "google",
    name: "Google AI (Gemini)",
    category: "direct_api",
    websiteUrl: "https://ai.google.dev",
    apiDocsUrl: "https://ai.google.dev/gemini-api/docs",
    pricingUrl: "https://ai.google.dev/pricing",
    hasFreeTier: true,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: 15,
    rateLimitTpm: 1000000,
    dailyRequestLimit: 1500,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "Free tier subject to rate limits; not for production SLA.",
    status: "available",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "verified",
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "direct_api",
    websiteUrl: "https://openai.com",
    apiDocsUrl: "https://platform.openai.com/docs",
    pricingUrl: "https://openai.com/api/pricing/",
    hasFreeTier: true,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: 3,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "Free tier heavily rate-limited; best-effort only.",
    status: "limited",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "likely",
  },
  {
    id: "anthropic",
    name: "Anthropic (Claude)",
    category: "direct_api",
    websiteUrl: "https://www.anthropic.com",
    apiDocsUrl: "https://docs.anthropic.com",
    pricingUrl: "https://www.anthropic.com/pricing",
    hasFreeTier: false,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: null,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: true,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "No free API tier. claude.ai offers a free consumer plan (not API).",
    status: "unknown",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "verified",
  },
  {
    id: "meta",
    name: "Meta (Llama)",
    category: "hosted_oss",
    websiteUrl: "https://www.llama.com",
    apiDocsUrl: "https://github.com/meta-llama/llama-models",
    pricingUrl: "https://www.llama.com",
    hasFreeTier: false,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: null,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: false,
    geographicRestrictions: [],
    termsRestrictions: "Open weights; self-host or use a third-party inference provider.",
    status: "available",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "verified",
  },
  {
    id: "mistral",
    name: "Mistral AI",
    category: "direct_api",
    websiteUrl: "https://mistral.ai",
    apiDocsUrl: "https://docs.mistral.ai",
    pricingUrl: "https://mistral.ai/pricing",
    hasFreeTier: true,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: 1,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "La Plateforme free tier very limited (1 req/s, daily cap).",
    status: "limited",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "likely",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    category: "direct_api",
    websiteUrl: "https://www.deepseek.com",
    apiDocsUrl: "https://api-docs.deepseek.com",
    pricingUrl: "https://platform.deepseek.com",
    hasFreeTier: true,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: 20,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "Free API tier with per-model rate limits; API may be unstable at peak.",
    status: "available",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "likely",
  },
  {
    id: "qwen",
    name: "Alibaba Qwen (DashScope)",
    category: "direct_api",
    websiteUrl: "https://qwen.ai",
    apiDocsUrl: "https://help.aliyun.com/zh/model-studio/",
    pricingUrl: "https://help.aliyun.com/zh/model-studio/models",
    hasFreeTier: true,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: null,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: ["CN"],
    termsRestrictions: "Free tier primarily for China-region accounts; open weights available globally.",
    status: "limited",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "likely",
  },
  {
    id: "groq",
    name: "Groq (LPU Inference)",
    category: "inference",
    websiteUrl: "https://groq.com",
    apiDocsUrl: "https://console.groq.com/docs",
    pricingUrl: "https://groq.com/pricing",
    hasFreeTier: true,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: 30,
    rateLimitTpm: 15000,
    dailyRequestLimit: 14400,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "Generous free tier for open models; daily token caps apply per model.",
    status: "available",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "verified",
  },
  {
    id: "together",
    name: "Together AI",
    category: "inference",
    websiteUrl: "https://www.together.ai",
    apiDocsUrl: "https://docs.together.ai",
    pricingUrl: "https://www.together.ai/pricing",
    hasFreeTier: true,
    freeCreditsAmount: 5,
    freeCreditsCurrency: "USD",
    rateLimitRpm: 60,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "$5 sign-up credits; some open models also have a free endpoint.",
    status: "available",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "verified",
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    category: "inference",
    websiteUrl: "https://fireworks.ai",
    apiDocsUrl: "https://docs.fireworks.ai",
    pricingUrl: "https://fireworks.ai/pricing",
    hasFreeTier: true,
    freeCreditsAmount: 1,
    freeCreditsCurrency: "USD",
    rateLimitRpm: null,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "Free trial credits on sign-up.",
    status: "available",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "likely",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "aggregator",
    websiteUrl: "https://openrouter.ai",
    apiDocsUrl: "https://openrouter.ai/docs",
    pricingUrl: "https://openrouter.ai/models",
    hasFreeTier: true,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: 20,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "Hosts many free models; free models are rate-limited and may be deprioritized.",
    status: "available",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "verified",
  },
  {
    id: "huggingface",
    name: "Hugging Face (Inference)",
    category: "hosted_oss",
    websiteUrl: "https://huggingface.co",
    apiDocsUrl: "https://huggingface.co/docs/api-inference",
    pricingUrl: "https://huggingface.co/pricing",
    hasFreeTier: true,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: 30,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "Serverless free inference, rate-limited; many open weights downloadable.",
    status: "available",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "verified",
  },
  {
    id: "cloudflare",
    name: "Cloudflare Workers AI",
    category: "cloud",
    websiteUrl: "https://workers.cloudflare.com",
    apiDocsUrl: "https://developers.cloudflare.com/workers-ai",
    pricingUrl: "https://developers.cloudflare.com/workers-ai/platform/pricing",
    hasFreeTier: true,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: null,
    rateLimitTpm: null,
    dailyRequestLimit: 10000,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "10,000 requests/day free on Workers Free plan.",
    status: "available",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "verified",
  },
  {
    id: "ollama",
    name: "Ollama",
    category: "local_platform",
    websiteUrl: "https://ollama.com",
    apiDocsUrl: "https://github.com/ollama/ollama",
    pricingUrl: "https://ollama.com",
    hasFreeTier: true,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: null,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: false,
    geographicRestrictions: [],
    termsRestrictions: "100% local, open-source. Runs on your own hardware.",
    status: "available",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "verified",
  },
  {
    id: "perplexity",
    name: "Perplexity (Sonar)",
    category: "direct_api",
    websiteUrl: "https://www.perplexity.ai",
    apiDocsUrl: "https://docs.perplexity.ai",
    pricingUrl: "https://www.perplexity.ai/pricing",
    hasFreeTier: true,
    freeCreditsAmount: 5,
    freeCreditsCurrency: "USD",
    rateLimitRpm: null,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "Free tier / trial credits for Sonar search models.",
    status: "limited",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "likely",
  },
  {
    id: "cohere",
    name: "Cohere",
    category: "direct_api",
    websiteUrl: "https://cohere.com",
    apiDocsUrl: "https://docs.cohere.com",
    pricingUrl: "https://cohere.com/pricing",
    hasFreeTier: true,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: null,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "Free trial credits via the playground / limited API access.",
    status: "limited",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "unverified",
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    category: "direct_api",
    websiteUrl: "https://x.ai",
    apiDocsUrl: "https://docs.x.ai",
    pricingUrl: "https://x.ai/api",
    hasFreeTier: false,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: null,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: true,
    requiresSignup: true,
    geographicRestrictions: [],
    termsRestrictions: "Primarily paid; free access via X platform, not the developer API.",
    status: "unknown",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "unverified",
  },
  {
    id: "microsoft",
    name: "Microsoft (Phi)",
    category: "hosted_oss",
    websiteUrl: "https://huggingface.co/microsoft",
    apiDocsUrl: "https://huggingface.co/microsoft/phi-4",
    pricingUrl: "https://azure.microsoft.com/products/ai-services",
    hasFreeTier: false,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: null,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: false,
    geographicRestrictions: [],
    termsRestrictions: "Open weights (MIT); use via Hugging Face or self-host. Azure API is paid.",
    status: "available",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "verified",
  },
  {
    id: "localai",
    name: "LocalAI",
    category: "local_platform",
    websiteUrl: "https://localai.io",
    apiDocsUrl: "https://localai.io",
    pricingUrl: "https://localai.io",
    hasFreeTier: true,
    freeCreditsAmount: null,
    freeCreditsCurrency: "USD",
    rateLimitRpm: null,
    rateLimitTpm: null,
    dailyRequestLimit: null,
    monthlyTokenLimit: null,
    requiresPaymentMethod: false,
    requiresSignup: false,
    geographicRestrictions: [],
    termsRestrictions: "Self-hosted OpenAI-compatible drop-in, fully free.",
    status: "available",
    lastVerifiedAt: SEED_DATE,
    verificationConfidence: "verified",
  },
];

export const HARNESSES: Harness[] = [
  {
    id: "claude-code",
    name: "Claude Code",
    websiteUrl: "https://claude.com/claude-code",
    documentationUrl: "https://docs.anthropic.com/en/docs/claude-code",
    supportsCustomOpenaiEndpoint: false,
    supportsAnthropicEndpoint: true,
    supportsOpenrouterRouting: false,
    authMethods: ["api_key"],
    description:
      "Anthropic's agentic coding CLI. Talks to the Anthropic API by default; recent versions allow a custom Anthropic-compatible base URL.",
  },
  {
    id: "opencode",
    name: "OpenCode",
    websiteUrl: "https://opencode.ai",
    documentationUrl: "https://opencode.ai/docs",
    supportsCustomOpenaiEndpoint: true,
    supportsAnthropicEndpoint: true,
    supportsOpenrouterRouting: true,
    authMethods: ["api_key", "none"],
    description:
      "Open-source coding agent. Works with any OpenAI-compatible endpoint, Anthropic endpoints, OpenRouter, and fully local providers (Ollama).",
  },
  {
    id: "cline",
    name: "Cline",
    websiteUrl: "https://cline.bot",
    documentationUrl: "https://docs.cline.bot",
    supportsCustomOpenaiEndpoint: true,
    supportsAnthropicEndpoint: true,
    supportsOpenrouterRouting: true,
    authMethods: ["api_key"],
    description:
      "VS Code extension. Supports OpenAI-compatible base URLs, OpenRouter, and Anthropic directly.",
  },
  {
    id: "roo-code",
    name: "Roo Code",
    websiteUrl: "https://roocode.com",
    documentationUrl: "https://docs.roocode.com",
    supportsCustomOpenaiEndpoint: true,
    supportsAnthropicEndpoint: true,
    supportsOpenrouterRouting: true,
    authMethods: ["api_key"],
    description:
      "Fork of Cline with custom modes. Same endpoint flexibility (OpenAI-compatible, OpenRouter, Anthropic).",
  },
  {
    id: "aider",
    name: "Aider",
    websiteUrl: "https://aider.chat",
    documentationUrl: "https://aider.chat/docs",
    supportsCustomOpenaiEndpoint: true,
    supportsAnthropicEndpoint: true,
    supportsOpenrouterRouting: true,
    authMethods: ["api_key", "none"],
    description:
      "Terminal pair-programmer. Broad provider support including local OpenAI-compatible servers and OpenRouter.",
  },
  {
    id: "continue",
    name: "Continue",
    websiteUrl: "https://continue.dev",
    documentationUrl: "https://docs.continue.dev",
    supportsCustomOpenaiEndpoint: true,
    supportsAnthropicEndpoint: true,
    supportsOpenrouterRouting: true,
    authMethods: ["api_key", "none"],
    description:
      "Open-source AI code assistant for IDEs. Supports local models (Ollama/LM Studio) and remote OpenAI-compatible endpoints.",
  },
  {
    id: "cursor",
    name: "Cursor",
    websiteUrl: "https://cursor.com",
    documentationUrl: "https://docs.cursor.com",
    supportsCustomOpenaiEndpoint: false,
    supportsAnthropicEndpoint: false,
    supportsOpenrouterRouting: false,
    authMethods: ["api_key", "oauth"],
    description:
      "Commercial AI IDE. Ships its own model roster; does not accept arbitrary BYO endpoints easily.",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    websiteUrl: "https://windsurf.com",
    documentationUrl: "https://docs.windsurf.com",
    supportsCustomOpenaiEndpoint: false,
    supportsAnthropicEndpoint: false,
    supportsOpenrouterRouting: false,
    authMethods: ["api_key", "oauth"],
    description:
      "Commercial AI IDE (formerly Codeium). Proprietary model access; limited BYO.",
  },
];

export const MODELS: Model[] = [
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    providerId: "google",
    family: "Gemini",
    version: "2.0",
    releaseDate: "2024-12-01",
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text", "image"],
    visionSupport: true,
    toolCalling: true,
    structuredOutput: true,
    reasoningSupport: true,
    codingCapability: 4,
    isOpenSource: false,
    license: "Proprietary",
    officialPageUrl: "https://ai.google.dev/gemini-api/docs/models",
    documentationUrl: "https://ai.google.dev/gemini-api/docs/models/gemini-v2",
    description:
      "Google's fast multimodal flagship. Strong coding and vision, 1M context, free tier via the Gemini API.",
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash-Lite",
    providerId: "google",
    family: "Gemini",
    version: "2.0",
    releaseDate: "2024-12-01",
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    visionSupport: true,
    toolCalling: true,
    structuredOutput: true,
    reasoningSupport: false,
    codingCapability: 3,
    isOpenSource: false,
    license: "Proprietary",
    officialPageUrl: "https://ai.google.dev/gemini-api/docs/models",
    documentationUrl: "https://ai.google.dev/gemini-api/docs/models/gemini-v2",
    description: "Cost-efficient variant of Flash. Vision + tools, 1M context, free tier.",
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    providerId: "google",
    family: "Gemini",
    version: "2.5",
    releaseDate: "2025-04-01",
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    inputModalities: ["text", "image", "audio"],
    outputModalities: ["text"],
    visionSupport: true,
    toolCalling: true,
    structuredOutput: true,
    reasoningSupport: true,
    codingCapability: 4,
    isOpenSource: false,
    license: "Proprietary",
    officialPageUrl: "https://ai.google.dev/gemini-api/docs/models",
    documentationUrl: "https://ai.google.dev/gemini-api/docs/models/gemini-v2-5",
    description: "Next-gen Flash with thinking/reasoning and larger output. Free tier via Gemini API.",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o mini",
    providerId: "openai",
    family: "GPT",
    version: "4o-mini",
    releaseDate: "2024-07-18",
    contextWindow: 128000,
    maxOutputTokens: 16384,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    visionSupport: true,
    toolCalling: true,
    structuredOutput: true,
    reasoningSupport: false,
    codingCapability: 3,
    isOpenSource: false,
    license: "Proprietary",
    officialPageUrl: "https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/",
    documentationUrl: "https://platform.openai.com/docs/models/gpt-4o-mini",
    description: "Small, cheap, multimodal OpenAI model. Available on the limited free tier.",
  },
  {
    id: "gpt-4.1-mini",
    name: "GPT-4.1 mini",
    providerId: "openai",
    family: "GPT",
    version: "4.1-mini",
    releaseDate: "2025-04-14",
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    visionSupport: true,
    toolCalling: true,
    structuredOutput: true,
    reasoningSupport: false,
    codingCapability: 4,
    isOpenSource: false,
    license: "Proprietary",
    officialPageUrl: "https://openai.com/index/gpt-4-1/",
    documentationUrl: "https://platform.openai.com/docs/models/gpt-4.1-mini",
    description: "Mid-tier GPT-4.1 with 1M context. Available on the limited free tier.",
  },
  {
    id: "llama-3.3-70b",
    name: "Llama 3.3 70B Instruct",
    providerId: "meta",
    family: "Llama",
    version: "3.3",
    releaseDate: "2024-12-06",
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: true,
    structuredOutput: false,
    reasoningSupport: false,
    codingCapability: 4,
    isOpenSource: true,
    license: "Llama 3.3 Community",
    officialPageUrl: "https://www.llama.com",
    documentationUrl: "https://github.com/meta-llama/llama-models",
    description: "Meta's open-weight 70B. Distributed free via Groq, Together, Ollama, and others.",
  },
  {
    id: "llama-3.1-8b",
    name: "Llama 3.1 8B Instruct",
    providerId: "meta",
    family: "Llama",
    version: "3.1",
    releaseDate: "2024-07-23",
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: true,
    structuredOutput: false,
    reasoningSupport: false,
    codingCapability: 3,
    isOpenSource: true,
    license: "Llama 3.1 Community",
    officialPageUrl: "https://www.llama.com",
    documentationUrl: "https://github.com/meta-llama/llama-models",
    description: "Small open-weight Llama, ideal for local and cheap inference.",
  },
  {
    id: "llama-3.2-11b-vision",
    name: "Llama 3.2 11B Vision",
    providerId: "meta",
    family: "Llama",
    version: "3.2",
    releaseDate: "2024-09-25",
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    visionSupport: true,
    toolCalling: false,
    structuredOutput: false,
    reasoningSupport: false,
    codingCapability: 3,
    isOpenSource: true,
    license: "Llama 3.2 Community",
    officialPageUrl: "https://www.llama.com",
    documentationUrl: "https://github.com/meta-llama/llama-models",
    description: "Open-weight vision-language model. Free via Groq and Ollama.",
  },
  {
    id: "llama-3.2-90b-vision",
    name: "Llama 3.2 90B Vision",
    providerId: "meta",
    family: "Llama",
    version: "3.2",
    releaseDate: "2024-09-25",
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    visionSupport: true,
    toolCalling: false,
    structuredOutput: false,
    reasoningSupport: false,
    codingCapability: 3,
    isOpenSource: true,
    license: "Llama 3.2 Community",
    officialPageUrl: "https://www.llama.com",
    documentationUrl: "https://github.com/meta-llama/llama-models",
    description: "Larger open-weight vision model. Free via Groq.",
  },
  {
    id: "mistral-7b",
    name: "Mistral 7B Instruct",
    providerId: "mistral",
    family: "Mistral",
    version: "7B",
    releaseDate: "2023-09-27",
    contextWindow: 32000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: true,
    structuredOutput: false,
    reasoningSupport: false,
    codingCapability: 3,
    isOpenSource: true,
    license: "Apache-2.0",
    officialPageUrl: "https://mistral.ai/news/mistral-7b",
    documentationUrl: "https://docs.mistral.ai",
    description: "Classic open-weight 7B. Free via Mistral free tier, Together, Groq, Ollama.",
  },
  {
    id: "mistral-small-3",
    name: "Mistral Small 3",
    providerId: "mistral",
    family: "Mistral",
    version: "Small-3",
    releaseDate: "2025-01-01",
    contextWindow: 32000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: true,
    structuredOutput: true,
    reasoningSupport: false,
    codingCapability: 3,
    isOpenSource: true,
    license: "Apache-2.0",
    officialPageUrl: "https://mistral.ai/news/mistral-small-3",
    documentationUrl: "https://docs.mistral.ai",
    description: "Open-weight small model with strong instruction following.",
  },
  {
    id: "mixtral-8x7b",
    name: "Mixtral 8x7B Instruct",
    providerId: "mistral",
    family: "Mixtral",
    version: "8x7B",
    releaseDate: "2023-12-11",
    contextWindow: 32000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: true,
    structuredOutput: false,
    reasoningSupport: false,
    codingCapability: 3,
    isOpenSource: true,
    license: "Apache-2.0",
    officialPageUrl: "https://mistral.ai/news/mixtral-of-experts",
    documentationUrl: "https://docs.mistral.ai",
    description: "Sparse MoE open-weight model. Free via Together, Groq, Ollama.",
  },
  {
    id: "codestral",
    name: "Codestral",
    providerId: "mistral",
    family: "Codestral",
    version: "25.01",
    releaseDate: "2025-01-13",
    contextWindow: 256000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: false,
    structuredOutput: false,
    reasoningSupport: false,
    codingCapability: 5,
    isOpenSource: false,
    license: "Mistral Commercial",
    officialPageUrl: "https://mistral.ai/news/codestral",
    documentationUrl: "https://docs.mistral.ai",
    description: "Code-specialized model. Free via Mistral's coding endpoint and Together.",
  },
  {
    id: "deepseek-chat",
    name: "DeepSeek V3 (Chat)",
    providerId: "deepseek",
    family: "DeepSeek",
    version: "V3",
    releaseDate: "2024-12-26",
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: true,
    structuredOutput: true,
    reasoningSupport: false,
    codingCapability: 4,
    isOpenSource: true,
    license: "MIT",
    officialPageUrl: "https://github.com/deepseek-ai/DeepSeek-V3",
    documentationUrl: "https://api-docs.deepseek.com",
    description: "Strong open-weight general model. Generous free API + open weights.",
  },
  {
    id: "deepseek-reasoner",
    name: "DeepSeek R1",
    providerId: "deepseek",
    family: "DeepSeek",
    version: "R1",
    releaseDate: "2025-01-20",
    contextWindow: 64000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: false,
    structuredOutput: false,
    reasoningSupport: true,
    codingCapability: 4,
    isOpenSource: true,
    license: "MIT",
    officialPageUrl: "https://github.com/deepseek-ai/DeepSeek-R1",
    documentationUrl: "https://api-docs.deepseek.com/guides/reasoning_model",
    description: "Open-weight reasoning model. Free API tier and open weights.",
  },
  {
    id: "qwen2.5-72b",
    name: "Qwen2.5 72B Instruct",
    providerId: "qwen",
    family: "Qwen",
    version: "2.5",
    releaseDate: "2024-09-19",
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: true,
    structuredOutput: true,
    reasoningSupport: false,
    codingCapability: 4,
    isOpenSource: true,
    license: "Apache-2.0",
    officialPageUrl: "https://qwen.ai",
    documentationUrl: "https://help.aliyun.com/zh/model-studio/",
    description: "Open-weight 72B. Free tier via DashScope and open weights globally.",
  },
  {
    id: "qwen2.5-coder-32b",
    name: "Qwen2.5 Coder 32B",
    providerId: "qwen",
    family: "Qwen",
    version: "2.5-Coder",
    releaseDate: "2024-11-12",
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: true,
    structuredOutput: true,
    reasoningSupport: false,
    codingCapability: 5,
    isOpenSource: true,
    license: "Apache-2.0",
    officialPageUrl: "https://qwen.ai",
    documentationUrl: "https://help.aliyun.com/zh/model-studio/",
    description: "Open-weight code-specialized 32B. Free via Together/OpenRouter and local.",
  },
  {
    id: "qwen2.5-vl-72b",
    name: "Qwen2.5 VL 72B",
    providerId: "qwen",
    family: "Qwen",
    version: "2.5-VL",
    releaseDate: "2025-01-01",
    contextWindow: 128000,
    maxOutputTokens: 8192,
    inputModalities: ["text", "image", "video"],
    outputModalities: ["text"],
    visionSupport: true,
    toolCalling: true,
    structuredOutput: false,
    reasoningSupport: false,
    codingCapability: 4,
    isOpenSource: true,
    license: "Apache-2.0",
    officialPageUrl: "https://qwen.ai",
    documentationUrl: "https://help.aliyun.com/zh/model-studio/",
    description: "Open-weight vision-language model with strong document understanding.",
  },
  {
    id: "phi-4",
    name: "Phi-4",
    providerId: "microsoft",
    family: "Phi",
    version: "4",
    releaseDate: "2024-12-12",
    contextWindow: 16000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: true,
    structuredOutput: true,
    reasoningSupport: false,
    codingCapability: 4,
    isOpenSource: true,
    license: "MIT",
    officialPageUrl: "https://huggingface.co/microsoft/phi-4",
    documentationUrl: "https://huggingface.co/microsoft/phi-4",
    description: "Microsoft's small-but-mighty open-weight model (14B). Free via HF/Ollama.",
  },
  {
    id: "gemma-2-9b",
    name: "Gemma 2 9B",
    providerId: "google",
    family: "Gemma",
    version: "2",
    releaseDate: "2024-06-27",
    contextWindow: 8000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: false,
    structuredOutput: false,
    reasoningSupport: false,
    codingCapability: 3,
    isOpenSource: true,
    license: "Gemma",
    officialPageUrl: "https://huggingface.co/google/gemma-2-9b",
    documentationUrl: "https://ai.google.dev/gemma",
    description: "Google's open-weight 9B. Free via Groq, HF, Ollama.",
  },
  {
    id: "gemma-2-27b",
    name: "Gemma 2 27B",
    providerId: "google",
    family: "Gemma",
    version: "2",
    releaseDate: "2024-06-27",
    contextWindow: 8000,
    maxOutputTokens: 8192,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: false,
    structuredOutput: false,
    reasoningSupport: false,
    codingCapability: 3,
    isOpenSource: true,
    license: "Gemma",
    officialPageUrl: "https://huggingface.co/google/gemma-2-27b",
    documentationUrl: "https://ai.google.dev/gemma",
    description: "Google's open-weight 27B. Free via Groq, Together, Ollama.",
  },
  {
    id: "command-r",
    name: "Command R",
    providerId: "cohere",
    family: "Command",
    version: "R",
    releaseDate: "2024-08-30",
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: true,
    structuredOutput: true,
    reasoningSupport: false,
    codingCapability: 3,
    isOpenSource: false,
    license: "CC-BY-NC (weights) / Proprietary API",
    officialPageUrl: "https://cohere.com/command",
    documentationUrl: "https://docs.cohere.com",
    description: "RAG/tool-use oriented model. Free trial credits via Cohere.",
  },
  {
    id: "command-r-plus",
    name: "Command R+",
    providerId: "cohere",
    family: "Command",
    version: "R+",
    releaseDate: "2024-08-30",
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: true,
    structuredOutput: true,
    reasoningSupport: false,
    codingCapability: 3,
    isOpenSource: false,
    license: "Proprietary",
    officialPageUrl: "https://cohere.com/command",
    documentationUrl: "https://docs.cohere.com",
    description: "Larger Command model. Free trial credits via Cohere.",
  },
  {
    id: "sonar",
    name: "Sonar",
    providerId: "perplexity",
    family: "Sonar",
    version: "online",
    releaseDate: "2024-09-01",
    contextWindow: 127000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: false,
    structuredOutput: false,
    reasoningSupport: false,
    codingCapability: 2,
    isOpenSource: false,
    license: "Proprietary",
    officialPageUrl: "https://www.perplexity.ai/sonar",
    documentationUrl: "https://docs.perplexity.ai",
    description: "Search-augmented model with live web access. Free tier / trial credits.",
  },
  {
    id: "llama-3.1-70b",
    name: "Llama 3.1 70B Instruct",
    providerId: "meta",
    family: "Llama",
    version: "3.1",
    releaseDate: "2024-07-23",
    contextWindow: 128000,
    maxOutputTokens: 4096,
    inputModalities: ["text"],
    outputModalities: ["text"],
    visionSupport: false,
    toolCalling: true,
    structuredOutput: false,
    reasoningSupport: false,
    codingCapability: 4,
    isOpenSource: true,
    license: "Llama 3.1 Community",
    officialPageUrl: "https://www.llama.com",
    documentationUrl: "https://github.com/meta-llama/llama-models",
    description: "Open-weight 70B. Free via Groq, Together, Ollama.",
  },
];
